# zsh settings
setopt autocd beep extendedglob nomatch notify interactivecomments
bindkey -e
bindkey "^[[3~" delete-char

# Download Znap, if it's not there yet.
[[ -r ~/znap-repos/znap/znap.zsh ]] ||
    git clone --depth 1 -- \
        https://github.com/marlonrichert/zsh-snap.git ~/znap-repos/znap
source ~/znap-repos/znap/znap.zsh  # Start Znap

# prompt first
znap eval starship 'starship init zsh'
znap prompt

# evals
znap eval zoxide "zoxide init zsh"

# completions
znap install zsh-users/zsh-completions
znap fpath _rustup "rustup completions zsh"
znap fpath _cargo "rustup completions zsh cargo"
znap fpath _starship "starship completions zsh"
znap fpath _atuin "atuin gen-completions --shell zsh"
znap fpath _jj "jj util completion zsh"

# plugins
znap source marlonrichert/zsh-autocomplete
znap source zsh-users/zsh-autosuggestions
znap source MichaelAquilina/zsh-auto-notify
znap source zsh-users/zsh-syntax-highlighting

# settings for marlonrichert/zsh-autocomplete
zstyle ':autocomplete:*complete*:*' insert-unambiguous yes # insert common substring
bindkey '\t' menu-complete "$terminfo[kcbt]" reverse-menu-complete # use tab/shift-tab to cycle completions

# settings for zsh-syntax-highlighting
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan' # make paths blue
ZSH_HIGHLIGHT_STYLES[precommand]='none' # stop sudo from being underlined

# settings for zsh-auto-notify
AUTO_NOTIFY_IGNORE+=("hx")

# need atuin to be last
znap eval atuin "atuin init zsh"
