{ lib, config, ... }:
{
  options = {
    my.services.podman = {
      enable = lib.mkEnableOption "podman";
    };
  };

  config = lib.mkIf config.my.services.podman.enable {
    # i'd rather allow all traffic from containers to be let through to the host
    # than have to open up said host to the world with `networking.firewall.allowedTCPPorts`
    networking.firewall.trustedInterfaces = [
      (if !config.networking.nftables.enable then "podman+" else "podman*")
    ];

    # Auto-generated by compose2nix.

    # Runtime
    virtualisation.podman.enable = true;
    virtualisation.podman.autoPrune.enable = true;
    virtualisation.podman.dockerCompat = true;
    virtualisation.podman.defaultNetwork.settings.dns_enabled = true;

    # Enable container name DNS for all Podman networks.
    networking.firewall.interfaces =
      let
        matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
      in
      {
        "${matchAll}".allowedUDPPorts = [ 53 ];
      };

    virtualisation.oci-containers.backend = "podman";

    my.services.postgres.extraAuth = [
      ''
        # let connections from the default podman network log into their own databases
        host sameuser all 10.88.0.0/16 password
      ''
    ];
  };
}
