{
  lib,
  config,
  ...
}:
{
  options = {
    my.services.sure = {
      enable = lib.mkEnableOption "sure finance, using systemwide postgres/redis + containerised web/worker";
    };
  };

  config = lib.mkIf config.my.services.sure.enable {
    my.services.podman.enable = true;
    my.services.redis.enable = true;

    my.services.postgres.enable = true;
    my.services.postgres.users = [ "sure" ];

    # Auto-generated by compose2nix from https://github.com/we-promise/sure/blob/1ff78bddf27b9c584cbd59a3d10d2fa156990a4d/compose.example.yml
    virtualisation.oci-containers.containers =
      let
        image = "ghcr.io/we-promise/sure:stable";
        extraOptions = [ "--pull=newer" ];
        volumes = [
          "/var/lib/sure/app:/rails/storage:U"
        ];

        environment = {
          DB_HOST = "host.containers.internal";
          DB_PORT = "5432";
          POSTGRES_DB = "sure";
          POSTGRES_PASSWORD = "sure";
          POSTGRES_USER = "sure";
          REDIS_URL = "redis://:valkeyisawesomeactually@host.containers.internal:6379";
          RAILS_ASSUME_SSL = "false";
          RAILS_FORCE_SSL = "false";
          SELF_HOSTED = "true";
          BINDING = "::"; # ipv6
          SECRET_KEY_BASE = "c3e4e489c108a2926ccc09240fbb57e8d2c29538e4444a18996dc74864f47c058724b003acd2f1df5aac6bc4f7ea45b1a33d7346626357ffa305df2016c34aee";
        };
      in
      {
        sure-web = {
          inherit
            image
            extraOptions
            environment
            volumes
            ;

          serviceName = "sure-web";
          ports = [
            "3000:3000/tcp"
          ];
        };

        sure-worker = {
          inherit
            image
            extraOptions
            environment
            volumes
            ;

          serviceName = "sure-worker";
          cmd = [
            "bundle"
            "exec"
            "sidekiq"
          ];
        };
      };

    systemd.services =
      let
        serviceConfig = {
          Restart = lib.mkForce "always";
        };
        partOf = [
          "sure.target"
        ];
        wantedBy = [
          "sure.target"
        ];
      in
      {
        sure-worker = { inherit serviceConfig partOf wantedBy; };
        sure-web = { inherit serviceConfig partOf wantedBy; };
      };

    # root service
    # when started, this will automatically start the containers.
    # when stopped, this will teardown all resources.
    systemd.targets.sure = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };

    # ensure directories exist with proper permissions
    # copied from https://github.com/not-matthias/dotfiles-nix/blob/8453ecb959c8945cca7ecb0ca7a39206e045f608/modules/system/services/sure.nix
    systemd.tmpfiles.rules = [
      "d /var/lib/sure 0755 root root -"
      "d /var/lib/sure/app 0755 root root -"
    ];

    services.caddy.virtualHosts = lib.mkIf config.my.services.tailscale.enable {
      "sure:80" = {
        extraConfig = ''
          bind tailscale/sure
          reverse_proxy localhost:3000
        '';
      };
    };
  };
}
